server:
  port: ${PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dropvault}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

storage:
  location: ${STORAGE_LOCATION:storage}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000